-- Local development seed.
--
-- Local only: never run this against production.
--
-- Creates a ready-to-log-in demo account (username `default`, password
-- `default1234`, mailbox `dev@example.test`).
--
-- The account is intentionally NOT an admin: `isInitialized()` treats "an admin
-- exists" as "the instance is set up", so seeding an admin would skip the setup
-- wizard. Finish `/api/setup/init` in the browser first, then promote this
-- account if you need admin features locally:
--
--   INSERT INTO users (id, username, password_hash, is_admin)
--   VALUES ('user_default', 'default', 'x', 1)
--   ON CONFLICT(id) DO UPDATE SET is_admin = 1;
--
-- The password hash below is generated by `bun ./scripts/hash-password.ts default1234`
-- and is verified by `packages/worker/src/auth.ts`. Regenerate it there instead of
-- hand-editing, otherwise the login silently fails.

INSERT INTO users (id, username, password_hash, is_admin)
VALUES (
  'user_default',
  'default',
  'pbkdf2$100000$Bs3B7U7jaZhjeUIhKgomWQ$MAq7cEcVXhEyRe85yDAlAvKSLBKNFVKt4xqB_Bqzpw4',
  0
)
ON CONFLICT(id) DO NOTHING;

INSERT INTO mailboxes (id, user_id, address, is_active)
VALUES ('mailbox_dev_default', 'user_default', 'dev@example.test', 1)
ON CONFLICT(id) DO NOTHING;

INSERT OR IGNORE INTO domains (id, domain, is_active) VALUES ('domain_example_test', 'example.test', 1);
INSERT OR IGNORE INTO app_settings (key, value) VALUES ('allow_register', '0');
INSERT OR IGNORE INTO app_settings (key, value) VALUES ('max_aliases', '3');
